spring:
  application:
    name: basic-ticketing-app

  datasource:
    url: jdbc:mysql://j1r4n2ztuwm0bhh5.cbetxkdyhwsb.us-east-1.rds.amazonaws.com/o9ef7u0x1gfvaob7
    username: u2fk0dj1v2nctofy
    password: fy9u1ygx7blutabn
    driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  address: 0.0.0.0
