spring:
  application:
    name: basic-ticketing-app

  datasource:
    url: jdbc:mysql://j1r4n2ztuwm0bhh5.cbetxkdyhwsb.us-east-1.rds.amazonaws.com/vw47ogm46o22ss1d
    username: qxauk02l0m8ftahq
    password: gk2cutpw6y7xp3uc
    driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  address: 0.0.0.0
