spring:
  application:
    name: basic-ticketing-app

  datasource:
    url: jdbc:mysql://j1r4n2ztuwm0bhh5.cbetxkdyhwsb.us-east-1.rds.amazonaws.com/vw47ogm46o22ss1d
    username: lbpt2ski2hiddl2k
    password: di3bbsi51lfpqo3p
    driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  address: 0.0.0.0
